#pragma once

/**
@file
Subclass of ICPD_frm, which is generated by wxFormBuilder.
*/

#include <string>
#include <iostream>
#include <strstream>
#include <list>
#include <wx/wx.h>
#include <wx/utils.h> 

#include "clayout.h"
#include "designmng.h"
#include "wxautocell.h"
#include "wxrules.h"
#include "wxcircuit.h"
#include "wxfp.h"
#include "wxpreferences.h"
#include "wxabout.h"
#include "wxinterface.h"

class DesignMng;
class WxAutoCell;
class WxRules;
class WxCircuit;
class WxFP;
class WxPreferences;
class WxAbout;

/** Implementing ICPD_frm */
class IcpdFrm : public ICPD_frm{
public:
    /** Constructor */
    IcpdFrm( wxWindow* parent );
    
    DesignMng* getDesign(){return &designmng;};
    void viewLayout( string cellName );
    void executeCommand(string cmd);
    void refresh();

protected:
	// Frame events
	void OnClose(wxCloseEvent& event);
	void CmdKeyDown( wxKeyEvent& event );
	void PressedKey( wxKeyEvent& event );

	// File->New
	void newDesign( wxCommandEvent& event );
	void newCell( wxCommandEvent& event );

	// File->Load
	void loadProject( wxCommandEvent& event );
	void loadTech( wxCommandEvent& event );
	void loadSpiceNetlist( wxCommandEvent& event );
	void loadLayouts( wxCommandEvent& event );
	void loadPlacement( wxCommandEvent& event );
	void loadRouting( wxCommandEvent& event );

	// File->Save
	void saveProject( wxCommandEvent& event );
	void saveTech( wxCommandEvent& event );
	void saveSpiceNetlist( wxCommandEvent& event );
	void saveLayouts( wxCommandEvent& event );
	void savePlacement( wxCommandEvent& event );
	void saveRouting( wxCommandEvent& event );

	// File->Import
	void importSpiceNetlist( wxCommandEvent& event );
	void importLEF( wxCommandEvent& event );	

	// File->Export
	void exportLayout( wxCommandEvent& event );
	void exportCellSizes( wxCommandEvent& event );
	void exportPlacement( wxCommandEvent& event );	

	// File Script
	void flReadScript( wxCommandEvent& event );
	void saveHistory( wxCommandEvent& event );

	// File Exit
	void OnFileExit( wxCommandEvent& event );

	// View
	void showTech( wxCommandEvent& event );
	void showCircuit( wxCommandEvent& event );
	void showPreferences( wxCommandEvent& event );

	// Cells
	void showCellgen( wxCommandEvent& event );
	void calcPinsPos( wxCommandEvent& event );

	// Place
	void showFP( wxCommandEvent& event );
	void plTerminals( wxCommandEvent& event );
	void fastp( wxCommandEvent& event );
	void plVerify( wxCommandEvent& event );
	void plAutoFlip( wxCommandEvent& event );	
	void plIncremental( wxCommandEvent& event );
	void plWL( wxCommandEvent& event );

	// Route
	void rotdl( wxCommandEvent& event );
	void pfinder( wxCommandEvent& event );
	void rtOptimize( wxCommandEvent& event );
	void rtCompact( wxCommandEvent& event );
	void rtClear( wxCommandEvent& event );

	// Help
	void HelpaboutClick( wxCommandEvent& event );
	void helpHP( wxCommandEvent& event );

	// Tools
	void refreshIcon( wxCommandEvent& event );

	// List Boxes
	void layoutListEvent( wxCommandEvent& event );
	void viewLayout( wxCommandEvent& event );
	void openInstancewindow( wxCommandEvent& event );
	void printInstance( wxCommandEvent& event );
	void printCell( wxCommandEvent& event );
	void printNet( wxCommandEvent& event );
	void printInterface( wxCommandEvent& event );

	// Shell
	void command( wxCommandEvent& event );

private:
    DesignMng designmng;
    WxRules *wxrules;
    WxAutoCell *wxautocell;
    WxCircuit *wxcircuit;
    WxFP *wxfp;
    WxPreferences *wxpreferences;
    WxAbout *wxabout;
    
    list <CLayout*> instanceLevel;
    int pos;
    
    void refreshInstanceList();
};