#pragma once

/**
@file
Subclass of Help_About, which is generated by wxFormBuilder.
*/

#include "wxinterface.h"
#include "util.h"

/** Implementing Help_About */
class WxAbout : public Help_About{
protected:
	void hide( wxCloseEvent& event );

public:
	/** Constructor */
	WxAbout( wxWindow* parent );
};