#ifndef __WXAUTOCELL__
#define __WXAUTOCELL__

/**
@file
Subclass of CellGen, which is generated by wxFormBuilder.
*/

#include "wxinterface.h"
#include "icpdfrm.h"

class IcpdFrm;

/** Implementing CellGen */
class WxAutoCell : public CellGen{
private:
	IcpdFrm* currentFrmwork;

protected:
	// Handlers for CellGen events.
	void PressedKey( wxKeyEvent& event );
	void hide( wxCloseEvent& event );
	//void generateAllCells( wxCommandEvent& event );
	void generateCell( wxCommandEvent& event );
	void select( wxCommandEvent& event );
	void fold( wxCommandEvent& event );
	void place( wxCommandEvent& event );
	void route( wxCommandEvent& event );
	void compact( wxCommandEvent& event );
	void view( wxCommandEvent& event );

	void update();
	
public:
	/** Constructor */
	WxAutoCell( IcpdFrm* frmwork );

	void refresh();
};

#endif // __WXAUTOCELL__
