#ifndef WXCIRCUIT
#define WXCIRCUIT

/**
@file
Subclass of Circuit, which is generated by wxFormBuilder.
*/

#include "wxinterface.h"
#include "icpdfrm.h"

class IcpdFrm;

/** Implementing Circuit */
class WxCircuit : public View_Circuit{
private:
	IcpdFrm* currentFrmwork;

protected:
	// Handlers for Circuit events.
	void PressedKey( wxKeyEvent& event );
	void hide( wxCloseEvent& event );
	void okButtonEvt( wxCommandEvent& event );
	void cancelButtonEvt( wxCommandEvent& event );
	void ok();
	void cancel();

public:
	/** Constructor */
	WxCircuit( IcpdFrm* frmwork );

	void refresh();
};

#endif // WXCIRCUIT