#ifndef WXPREFERENCES
#define WXPREFERENCES

/**
@file
Subclass of View_Preferences, which is generated by wxFormBuilder.
*/

#include "wxinterface.h"
#include "icpdfrm.h"

class IcpdFrm;

/** Implementing View_Preferences */
class WxPreferences : public View_Preferences{
private:
	IcpdFrm* currentFrmwork;

protected:
	// Handlers for View_Preferences events.
	void PressedKey( wxKeyEvent& event );
	void hide( wxCloseEvent& event );
	void okButtonEvt( wxCommandEvent& event );
	void cancelButtonEvt( wxCommandEvent& event );
	void plButton( wxCommandEvent& event );
	void rotdlButton( wxCommandEvent& event );
	void viewerButton( wxCommandEvent& event );
	void lpsolverButton( wxCommandEvent& event );
	void logButton( wxCommandEvent& event );
	void ok();
	void cancel();
	
public:
	/** Constructor */
	WxPreferences( IcpdFrm* frmwork );

	void refresh();
};

#endif // WXPREFERENCES
