#ifndef __WXRULES_h__
#define __WXRULES_h__

/**
@file
Subclass of Design_Rules, which is generated by wxFormBuilder.
*/

#include "wxinterface.h"
#include "icpdfrm.h"

using namespace std;

class IcpdFrm;

/** Implementing Design_Rules */
class WxRules : public Design_Rules{
private:
	IcpdFrm* currentFrmwork;

protected:
	// Handlers for Design_Rules events.
	void PressedKey( wxKeyEvent& event );
	void hide( wxCloseEvent& event );
	void saveButtonEvt( wxCommandEvent& event );
	void closeButtonEvt( wxCommandEvent& event );
	void selectRule( wxCommandEvent& event );
	void selectLayer( wxCommandEvent& event );
	void save();
	void close();

public:
	/** Constructor */
	WxRules( IcpdFrm* frmwork );

	void refresh();
};

#endif // __WXRULES_h__
